import = [
  "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-mocha.toml"
]

[font]
size=13.0

[font.normal]
family="MesloLGS Nerd Font"
style="regular"

[font.bold]
family = "MesloLGS Nerd Font"
style = "Bold"

[font.bold_italic]
family = "MesloLGS Nerd Font"
style = "Bold Italic"

[font.italic]
family = "MesloLGS Nerd Font"
style = "Italic"


[window]

dimensions = { columns = 0, lines = 0 }  # Default: columns = 0, lines = 0
padding = { x = 5, y = 5 }  # Default: x = 0, y = 0

decorations = "None"
decorations_theme_variant = "Dark"

opacity = 0.95  # Default: 1.0
title = "Terminal"  # Default: "Alacritty"

resize_increments = false  # Default: false

[scrolling]

history = 10000  # Default: 10000
multiplier = 3  # Default: 3

[cursor]

style = { shape = "Beam" , blinking = "Never" }
vi_mode_style = { shape = "Block" }

[mouse]

hide_when_typing = true
