# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true


format = """$directory$all$character"""

# Disable the package module, hiding it from the prompt completely

[git_branch]
symbol = ""

[aws]
disabled = true

[package]
disabled = true

[python]
disabled = true

[golang]
disabled = true

[c]
disabled = true

[cmake]
disabled = true

[conda]
disabled = true

[dart]
disabled = true

[java]
disabled = true

[meson]
disabled = true

[rlang]
disabled = true

[rust]
disabled = true

[swift]
disabled = true

[lua]
disabled = true
