# espanso match file

matches:
  - trigger: ":ma1"
    replace: "https://wiki.math.ntnu.no/tma4401/2025h/start"

  - trigger: ":ma2"
    replace: "https://wiki.math.ntnu.no/tma4413/2025h/start"

  - trigger: ":linmet"
    replace: "https://wiki.math.ntnu.no/tma4145/2025h/start"

  - trigger: ":nummat"
    replace: "https://wiki.math.ntnu.no/tma4215"

  - trigger: ":stokmod"
    replace: "https://wiki.math.ntnu.no/tma4265/2025h/start"

  - trigger: ":ringmod"
    replace: "https://wiki.math.ntnu.no/ma3201/2025h/start"

  - trigger: ":fsweb"
    replace: "https://fsweb.no/studentweb/login.jsf?faces-redirect=true&inst=FSNTNU"

  - trigger: ":bb"
    replace: "https://ntnu.blackboard.com/ultra/course"
  
  - trigger: ":fname"
    replace: "Jonathan Basil Broomfield Kjørlaug"

  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%d.%m.%Y"

  - trigger: ":shell"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo 'Hello from your shell'"
